// Generated by gencpp from file recherche_balle_tp1/command.msg
// DO NOT EDIT!


#ifndef RECHERCHE_BALLE_TP1_MESSAGE_COMMAND_H
#define RECHERCHE_BALLE_TP1_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace recherche_balle_tp1
{
template <class ContainerAllocator>
struct command_
{
  typedef command_<ContainerAllocator> Type;

  command_()
    : linearVelocity(0.0)
    , angularVelocity(0.0)
    , distance(0.0)
    , angle(0.0)  {
    }
  command_(const ContainerAllocator& _alloc)
    : linearVelocity(0.0)
    , angularVelocity(0.0)
    , distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _linearVelocity_type;
  _linearVelocity_type linearVelocity;

   typedef float _angularVelocity_type;
  _angularVelocity_type angularVelocity;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::recherche_balle_tp1::command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recherche_balle_tp1::command_<ContainerAllocator> const> ConstPtr;

}; // struct command_

typedef ::recherche_balle_tp1::command_<std::allocator<void> > command;

typedef boost::shared_ptr< ::recherche_balle_tp1::command > commandPtr;
typedef boost::shared_ptr< ::recherche_balle_tp1::command const> commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recherche_balle_tp1::command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recherche_balle_tp1::command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace recherche_balle_tp1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'recherche_balle_tp1': ['/home/projturtlebot/Documents/Release 1/ROS/ros_ws/src/TurtleBot-pkgs/recherche_balle_tp1/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::recherche_balle_tp1::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recherche_balle_tp1::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recherche_balle_tp1::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recherche_balle_tp1::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recherche_balle_tp1::command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recherche_balle_tp1::command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recherche_balle_tp1::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccc50d912f1f0832d43d62c9b0ebc68b";
  }

  static const char* value(const ::recherche_balle_tp1::command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccc50d912f1f0832ULL;
  static const uint64_t static_value2 = 0xd43d62c9b0ebc68bULL;
};

template<class ContainerAllocator>
struct DataType< ::recherche_balle_tp1::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recherche_balle_tp1/command";
  }

  static const char* value(const ::recherche_balle_tp1::command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recherche_balle_tp1::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linearVelocity      # m/s\n\
float32 angularVelocity     # rad/s\n\
float32 distance            # m\n\
float32 angle               # rad\n\
";
  }

  static const char* value(const ::recherche_balle_tp1::command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recherche_balle_tp1::command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linearVelocity);
      stream.next(m.angularVelocity);
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recherche_balle_tp1::command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recherche_balle_tp1::command_<ContainerAllocator>& v)
  {
    s << indent << "linearVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.linearVelocity);
    s << indent << "angularVelocity: ";
    Printer<float>::stream(s, indent + "  ", v.angularVelocity);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECHERCHE_BALLE_TP1_MESSAGE_COMMAND_H
